name: beta deploy

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test
      - name: deploy the app to github pages
        run: |
          echo "deploying the app to Github pages..."
          git config --global user.email ${{secrets.GHEMAIL}}
          git config --global user.name ${{secrets.GHUSERNAME}}
          git remote set-url origin https://${{secrets.GHUSERNAME}}:${{secrets.GHPASS}}@github.com/${{github.repository}}
          npm run deploy